data_filepath: data.txt
datetime_format: "%m/%d/%y %H:%M:%S"

width: 1000
height: 800
primary_font_size: 60
secondary_font_size: 30
primary_text_location_x: 200
primary_text_location_y: 150
secondary_text_location_x: 250
secondary_text_location_y: 500
warning_text_location_x: 100
warning_text_location_y: 100